server:
  port: 8085

spring:
  application:
    name: notification-service

  # distributed tracing with zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sample:
      probability: 1.0

  # kafka properties
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: account
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: "event:com.ewallet.notification.event.TransactionEvent"
#            trusted:
#              packages: '*'
#      properties:
#        spring:
#          json:
#            type:
#              mapping: "producer:com.ewallet.notification.event.TransactionEvent"
#            trusted:
#              packages: '*'
    # kafka topic events
    topic:
      name: account-event