server:
  port: 9999

spring:

  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  # distributed tracing with zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sample:
      probability: 1.0
  cloud:
    gateway:
      routes:
        ## User Service Route
        - id: user-service
          uri: lb://user-service # used lb to allow client side to do some load balancing
          predicates:
            - Path= /api/v1/auth/register, /api/v1/auth/login

        ## Account Service Route
        - id: account-service
          uri: lb://account-service # used lb to allow client side to do some load balancing
          predicates:
            - Path= /api/v1/account, /api/v1/account/deposit, /api/v1/account/withdraw
          filters:
            - AuthFilter

        ## Transaction Service Route
        - id: transaction-service
          uri: lb://transaction-service # used lb to allow client side to do some load balancing
          predicates:
            - Path= /api/v1/transaction
          filters:
            - AuthFilter

        ## Discovery Service Route
        - id: discovery-service
          uri: http://localhost:8761 # used lb to allow client side to do some load balancing
          predicates:
            - Path= /eureka/web
          filters:
            - SetPath= /

        ## Discovery Service Route
        - id: discovery-service-static-resource
          uri: http://localhost:8761 # used lb to allow client side to do some load balancing
          predicates:
            - Path= /eureka/**

# Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    prefer-ip-address: true
    hostname: localhost
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
    #            route:
    #              RouteDefinitionRouteLocator: INFO
    #            nodeValue: TRACE
    ## ROOT LOGGER OF THE WHOLE APPLICATION
    root: INFO

# Microservice health actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always

app:
  jwt:
    secret: secureApiGateway