server:
  port: 0

spring:

  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        ## User Service Route
        - id: user-service
          uri: lb://user-service # used lb to allow client side to do some load balancing
          predicates:
            - Path= /api/v1/auth/register, /api/v1/auth/login

        ## Account Service Route
        - id: account-service
          uri: lb://account-service # used lb to allow client side to do some load balancing
          predicates:
            - Path= /api/v1/account, /api/v1/account/deposit, /api/v1/account/withdraw

        ## Transaction Service Route
        - id: transaction-service
          uri: lb://transaction-service # used lb to allow client side to do some load balancing
          predicates:
            - Path= /api/v1/transaction

        ## Discovery Service Route
        - id: discovery-service
          uri: http://localhost:8761 # used lb to allow client side to do some load balancing
          predicates:
            - Path= /eureka/web
          filters:
            - SetPath= /

        ## Discovery Service Route
        - id: discovery-service-static-resource
          uri: http://localhost:8761 # used lb to allow client side to do some load balancing
          predicates:
            - Path= /eureka/**

# Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
    #            route:
    #              RouteDefinitionRouteLocator: INFO
    #            nodeValue: TRACE
    ## ROOT LOGGER OF THE WHOLE APPLICATION
    root: INFO

app:
  jwt:
    secret: secureApiGateway