server:
  port: 8081

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # enable_lazy_load_no_trans: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: andela

  # distributed tracing with zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sample:
      probability: 1.0

app:
  jwt:
    secret: tekanaeWalletJwtSecretKey
  authorities:
    USER: USER
    ADMIN: ADMIN

  baseUrl: "http://localhost"

## Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"

  instance:
    prefer-ip-address: true
    hostname: localhost


# Resilience4j Properties
resilience4j:
  circuitbreaker:
    instances:
      userService:
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        failureRateThreshold: '50' ## 50% request fails
        slidingWindowType: COUNT_BASED
        event-consumer-buffer-size: '10'
        registerHealthIndicator: 'true'
        waitDurationInOpenState: '5s'
        permittedNumberOfCallsInHalfOpenState: '3'
        slidingWindowSize: '5'
  retry:
    instances:
      userService:
        max-attempts: 3
        wait-duration: 5s # response duration


# Microservice health actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always