eureka:
  instance:
    hostname: localhost

  client:
    fetch-registry: false
    register-with-eureka: false

server:
  port: 8761

spring:
  # distributed tracing with zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sample:
      probability: 1.0