server:
  port: 8082

spring:
  application:
    name: account-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # enable_lazy_load_no_trans: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/accountservice
    username: postgres
    password: andela

  # distributed tracing with zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sample:
      probability: 1.0

  # kafka properties
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

    # kafka topic events
    topic:
      name: account-event

app:
  jwt:
    secret: tekanaeWalletJwtSecretKey
  authorities:
    USER: USER
    ADMIN: ADMIN

  baseUrl: "http://localhost"

# Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"

# Microservice health actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always

# Resilience4j Properties
resilience4j:
  circuitbreaker:
    instances:
      accountService:
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        failureRateThreshold: '50'
        slidingWindowType: COUNT_BASED
        event-consumer-buffer-size: '10'
        registerHealthIndicator: 'true'
        waitDurationInOpenState: '5s'
        permittedNumberOfCallsInHalfOpenState: '3'
        slidingWindowSize: '5'

