server:
  port: 8082

spring:
  application:
    name: account-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # enable_lazy_load_no_trans: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/accountservice
    username: postgres
    password: andela

app:
  jwt:
    secret: tekanaeWalletJwtSecretKey
  authorities:
    USER: USER
    ADMIN: ADMIN

  baseUrl: "http://localhost"

# Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"

# Microservice health actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: *
    health:
      show-details: always
